### PR TITLE
React/spartanny/set up pages

### PR DESCRIPTION
**Pull request by spartanny**
Issue #6 
Added routing for the following views with a dummy view :

- Homepage
- Category Page
- Product Page
- Checkout Page
- Success Page
- 404

### CODE REVIEW

**Comment by RedBlueKoi** [comment]
@spartanny Looks good, but why there is a new package installed?

**Comment by spartanny** [comment]
I was trying something in local

**Comment by RedBlueKoi** [comment]
Can you please remove it? I don't think we need this package 🙂

**Comment by spartanny** [comment]
Done !

**Review by RedBlueKoi — APPROVED** [review]

**Pull request merged**
